;;; bazel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bazel.el

(autoload 'bazel-build-mode "bazel"
"Major mode for editing Bazel BUILD files.

In addition to any hooks its parent mode `bazel-mode' might have run, this mode runs the hook
`bazel-build-mode-hook', as the final or penultimate step during initialization.

\\{bazel-build-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "BUILD" "BUILD.bazel") eos) #'bazel-build-mode))
(autoload 'bazel-workspace-mode "bazel"
"Major mode for editing Bazel WORKSPACE files.

In addition to any hooks its parent mode `bazel-mode' might have run, this mode runs the hook
`bazel-workspace-mode-hook', as the final or penultimate step during initialization.

\\{bazel-workspace-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "WORKSPACE" "WORKSPACE.bazel" "WORKSPACE.bzlmod") eos) #'bazel-workspace-mode))
(autoload 'bazel-module-mode "bazel"
"Major mode for editing Bazel module files.

In addition to any hooks its parent mode `bazel-mode' might have run, this mode runs the hook
`bazel-module-mode-hook', as the final or penultimate step during initialization.

\\{bazel-module-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx "/MODULE.bazel" eos) #'bazel-module-mode))
(autoload 'bazel-repo-mode "bazel"
"Major mode for editing REPO.bazel files.

In addition to any hooks its parent mode `bazel-mode' might have run, this mode runs the hook
`bazel-repo-mode-hook', as the final or penultimate step during initialization.

\\{bazel-repo-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx "/REPO.bazel" eos) #'bazel-repo-mode))
(autoload 'bazel-starlark-mode "bazel"
"Major mode for editing Bazel Starlark files.

In addition to any hooks its parent mode `bazel-mode' might have run, this mode runs the hook
`bazel-starlark-mode-hook', as the final or penultimate step during initialization.

\\{bazel-starlark-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (+ nonl) ".bzl" eos) #'bazel-starlark-mode))
(add-to-list 'auto-mode-alist (cons (rx "/MODULE.bazel.lock" eos) #'js-json-mode))
(autoload 'bazelrc-mode "bazel"
"Major mode for editing .bazelrc files.

In addition to any hooks its parent mode `conf-space-mode' might have run, this mode runs the hook
`bazelrc-mode-hook', as the final or penultimate step during initialization.

\\{bazelrc-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "bazel.bazelrc" ".bazelrc") eos) #'bazelrc-mode))
(add-to-list 'auto-mode-alist (cons (rx "/.bazelignore" eos) #'bazelignore-mode))
(autoload 'bazelignore-mode "bazel"
"Major mode for editing .bazelignore files.

In addition to any hooks its parent mode `prog-mode' might have run, this mode runs the hook
`bazelignore-mode-hook', as the final or penultimate step during initialization.

\\{bazelignore-mode-map}" t)
(autoload 'bazeliskrc-mode "bazel"
"Major mode derived from `conf-unix-mode' by `define-derived-mode'.
It inherits all of the parent's attributes, but has its own keymap,
abbrev table and syntax table:

  `bazeliskrc-mode-map', `bazeliskrc-mode-abbrev-table' and `bazeliskrc-mode-syntax-table'

which more-or-less shadow conf-unix-mode's corresponding tables.

In addition to any hooks its parent mode might have run, this mode runs the hook
`bazeliskrc-mode-hook', as the final or penultimate step during initialization.

\\{bazeliskrc-mode-map}" t)
(add-to-list 'auto-mode-alist (cons (rx "/.bazeliskrc" eos) #'bazeliskrc-mode))
(register-definition-prefixes "bazel" '("bazel"))

;;; End of scraped data

(provide 'bazel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bazel-autoloads.el ends here
