;;; puppet-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from puppet-mode.el

(autoload 'puppet-mode "puppet-mode"
"Major mode derived from `prog-mode' by `define-derived-mode'.
It inherits all of the parent's attributes, but has its own keymap,
abbrev table and syntax table:

  `puppet-mode-map', `puppet-mode-abbrev-table' and `puppet-mode-syntax-table'

which more-or-less shadow prog-mode's corresponding tables.

In addition to any hooks its parent mode might have run, this mode runs the hook `puppet-mode-hook',
as the final or penultimate step during initialization.

\\{puppet-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.pp\\'" . puppet-mode))
(register-definition-prefixes "puppet-mode" '("puppet-"))

;;; End of scraped data

(provide 'puppet-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; puppet-mode-autoloads.el ends here
