;;; presentation-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from presentation.el

(defvar presentation-mode nil
"Non-nil if Presentation mode is enabled.
See the `presentation-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `presentation-mode'.")
(custom-autoload 'presentation-mode "presentation" nil)
(autoload 'presentation-mode "presentation"
"Toggle Presentation mode ON or OFF.

This is a global minor mode.  If called interactively, toggle the
`Presentation mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='presentation-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{presentation-mode-map}

(fn &optional ARG)" t)
(register-definition-prefixes "presentation" '("presentation-"))

;;; End of scraped data

(provide 'presentation-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; presentation-autoloads.el ends here
