;;; rvm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from rvm.el

(autoload 'rvm-use-default "rvm" "\
use the rvm-default ruby as the current ruby version" t)
(autoload 'rvm-activate-corresponding-ruby "rvm" "\
activate the corresponding ruby version for the file in the current buffer.
This function searches for an .rvmrc file and activates the configured ruby.
If no .rvmrc file is found, the default ruby is used insted." t)
(autoload 'rvm-use "rvm" "\
switch the current ruby version to any ruby, which is installed with rvm

(fn NEW-RUBY NEW-GEMSET)" t)
(autoload 'rvm-open-gem "rvm" "\


(fn GEMHOME)" t)
(register-definition-prefixes "rvm" '("rvm"))

;;; End of scraped data

(provide 'rvm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rvm-autoloads.el ends here
