;;; color-theme-modern-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from aalto-dark-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "aalto-dark-theme" '("aalto-dark"))


;;; Generated autoloads from aalto-light-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "aalto-light-theme" '("aalto-light"))


;;; Generated autoloads from aliceblue-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "aliceblue-theme" '("aliceblue"))


;;; Generated autoloads from andreas-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "andreas-theme" '("andreas"))


;;; Generated autoloads from arjen-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "arjen-theme" '("arjen"))


;;; Generated autoloads from beige-diff-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "beige-diff-theme" '("beige-diff"))


;;; Generated autoloads from beige-eshell-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "beige-eshell-theme" '("beige-eshell"))


;;; Generated autoloads from bharadwaj-slate-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "bharadwaj-slate-theme" '("bharadwaj-slate"))


;;; Generated autoloads from bharadwaj-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "bharadwaj-theme" '("bharadwaj"))


;;; Generated autoloads from billw-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "billw-theme" '("billw"))


;;; Generated autoloads from black-on-gray-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "black-on-gray-theme" '("black-on-gray"))


;;; Generated autoloads from blippblopp-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blippblopp-theme" '("blippblopp"))


;;; Generated autoloads from blue-erc-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blue-erc-theme" '("blue-erc"))


;;; Generated autoloads from blue-eshell-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blue-eshell-theme" '("blue-eshell"))


;;; Generated autoloads from blue-gnus-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blue-gnus-theme" '("blue-gnus"))


;;; Generated autoloads from blue-mood-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blue-mood-theme" '("blue-mood"))


;;; Generated autoloads from blue-sea-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "blue-sea-theme" '("blue-sea"))


;;; Generated autoloads from calm-forest-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "calm-forest-theme" '("calm-forest"))


;;; Generated autoloads from charcoal-black-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "charcoal-black-theme" '("charcoal-black"))


;;; Generated autoloads from clarity-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "clarity-theme" '("clarity"))


;;; Generated autoloads from classic-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "classic-theme" '("classic"))


;;; Generated autoloads from cobalt-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "cobalt-theme" '("cobalt"))


;;; Generated autoloads from comidia-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "comidia-theme" '("comidia"))


;;; Generated autoloads from dark-blue-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-blue-theme" '("dark-blue"))


;;; Generated autoloads from dark-blue2-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-blue2-theme" '("dark-blue2"))


;;; Generated autoloads from dark-erc-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-erc-theme" '("dark-erc"))


;;; Generated autoloads from dark-font-lock-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-font-lock-theme" '("dark-font-lock"))


;;; Generated autoloads from dark-gnus-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-gnus-theme" '("dark-gnus"))


;;; Generated autoloads from dark-green-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-green-theme" '("dark-green"))


;;; Generated autoloads from dark-info-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-info-theme" '("dark-info"))


;;; Generated autoloads from dark-laptop-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "dark-laptop-theme" '("dark-laptop"))


;;; Generated autoloads from deep-blue-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "deep-blue-theme" '("deep-blue"))


;;; Generated autoloads from desert-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "desert-theme" '("desert"))


;;; Generated autoloads from digital-ofs1-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "digital-ofs1-theme" '("digital-ofs1"))


;;; Generated autoloads from emacs-21-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "emacs-21-theme" '("emacs-21"))


;;; Generated autoloads from emacs-nw-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "emacs-nw-theme" '("emacs-nw"))


;;; Generated autoloads from euphoria-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "euphoria-theme" '("euphoria"))


;;; Generated autoloads from feng-shui-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "feng-shui-theme" '("feng-shui"))


;;; Generated autoloads from fischmeister-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "fischmeister-theme" '("fischmeister"))


;;; Generated autoloads from gnome-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "gnome-theme" '("gnome"))


;;; Generated autoloads from gnome2-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "gnome2-theme" '("gnome2"))


;;; Generated autoloads from goldenrod-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "goldenrod-theme" '("goldenrod"))


;;; Generated autoloads from gray1-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "gray1-theme" '("gray1"))


;;; Generated autoloads from gray30-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "gray30-theme" '("gray30"))


;;; Generated autoloads from greiner-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "greiner-theme" '("greiner"))


;;; Generated autoloads from gtk-ide-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "gtk-ide-theme" '("gtk-ide"))


;;; Generated autoloads from high-contrast-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "high-contrast-theme" '("high-contrast"))


;;; Generated autoloads from hober-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "hober-theme" '("hober"))


;;; Generated autoloads from infodoc-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "infodoc-theme" '("infodoc"))


;;; Generated autoloads from jb-simple-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jb-simple-theme" '("jb-simple"))


;;; Generated autoloads from jedit-grey-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jedit-grey-theme" '("jedit-grey"))


;;; Generated autoloads from jonadabian-slate-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jonadabian-slate-theme" '("jonadabian-slate"))


;;; Generated autoloads from jonadabian-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jonadabian-theme" '("jonadabian"))


;;; Generated autoloads from jsc-dark-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jsc-dark-theme" '("jsc-dark"))


;;; Generated autoloads from jsc-light-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jsc-light-theme" '("jsc-light"))


;;; Generated autoloads from jsc-light2-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "jsc-light2-theme" '("jsc-light2"))


;;; Generated autoloads from julie-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "julie-theme" '("julie"))


;;; Generated autoloads from katester-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "katester-theme" '("katester"))


;;; Generated autoloads from kingsajz-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "kingsajz-theme" '("kingsajz"))


;;; Generated autoloads from late-night-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "late-night-theme" '("late-night"))


;;; Generated autoloads from lawrence-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "lawrence-theme" '("lawrence"))


;;; Generated autoloads from ld-dark-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "ld-dark-theme" '("ld-dark"))


;;; Generated autoloads from lethe-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "lethe-theme" '("lethe"))


;;; Generated autoloads from marine-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "marine-theme" '("marine"))


;;; Generated autoloads from marquardt-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "marquardt-theme" '("marquardt"))


;;; Generated autoloads from matrix-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "matrix-theme" '("matrix"))


;;; Generated autoloads from midnight-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "midnight-theme" '("midnight"))


;;; Generated autoloads from mistyday-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "mistyday-theme" '("mistyday"))


;;; Generated autoloads from montz-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "montz-theme" '("montz"))


;;; Generated autoloads from oswald-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "oswald-theme" '("oswald"))


;;; Generated autoloads from parus-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "parus-theme" '("parus"))


;;; Generated autoloads from pierson-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "pierson-theme" '("pierson"))


;;; Generated autoloads from pok-wob-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "pok-wob-theme" '("pok-wob"))


;;; Generated autoloads from pok-wog-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "pok-wog-theme" '("pok-wog"))


;;; Generated autoloads from railscast-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "railscast-theme" '("railscast"))


;;; Generated autoloads from ramangalahy-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "ramangalahy-theme" '("ramangalahy"))


;;; Generated autoloads from raspopovic-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "raspopovic-theme" '("raspopovic"))


;;; Generated autoloads from renegade-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "renegade-theme" '("renegade"))


;;; Generated autoloads from resolve-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "resolve-theme" '("resolve"))


;;; Generated autoloads from retro-green-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "retro-green-theme" '("retro-green"))


;;; Generated autoloads from retro-orange-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "retro-orange-theme" '("retro-orange"))


;;; Generated autoloads from robin-hood-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "robin-hood-theme" '("robin-hood"))


;;; Generated autoloads from rotor-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "rotor-theme" '("rotor"))


;;; Generated autoloads from ryerson-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "ryerson-theme" '("ryerson"))


;;; Generated autoloads from salmon-diff-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "salmon-diff-theme" '("salmon-diff"))


;;; Generated autoloads from salmon-font-lock-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "salmon-font-lock-theme" '("salmon-font-lock"))


;;; Generated autoloads from scintilla-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "scintilla-theme" '("scintilla"))


;;; Generated autoloads from shaman-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "shaman-theme" '("shaman"))


;;; Generated autoloads from simple-1-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "simple-1-theme" '("simple-1"))


;;; Generated autoloads from sitaramv-nt-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "sitaramv-nt-theme" '("sitaramv-nt"))


;;; Generated autoloads from sitaramv-solaris-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "sitaramv-solaris-theme" '("sitaramv-solaris"))


;;; Generated autoloads from snow-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "snow-theme" '("snow"))


;;; Generated autoloads from snowish-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "snowish-theme" '("snowish"))


;;; Generated autoloads from standard-ediff-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "standard-ediff-theme" '("standard-ediff"))


;;; Generated autoloads from standard-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "standard-theme" '("standard"))


;;; Generated autoloads from subdued-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "subdued-theme" '("subdued"))


;;; Generated autoloads from subtle-blue-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "subtle-blue-theme" '("subtle-blue"))


;;; Generated autoloads from subtle-hacker-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "subtle-hacker-theme" '("subtle-hacker"))


;;; Generated autoloads from taming-mr-arneson-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "taming-mr-arneson-theme" '("taming-mr-arneson"))


;;; Generated autoloads from taylor-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "taylor-theme" '("taylor"))


;;; Generated autoloads from tty-dark-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "tty-dark-theme" '("tty-dark"))


;;; Generated autoloads from vim-colors-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "vim-colors-theme" '("vim-colors"))


;;; Generated autoloads from whateveryouwant-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "whateveryouwant-theme" '("whateveryouwant"))


;;; Generated autoloads from wheat-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "wheat-theme" '("wheat"))


;;; Generated autoloads from word-perfect-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "word-perfect-theme" '("word-perfect"))


;;; Generated autoloads from xemacs-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "xemacs-theme" '("xemacs"))


;;; Generated autoloads from xp-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "xp-theme" 'nil)

;;; End of scraped data

(provide 'color-theme-modern-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; color-theme-modern-autoloads.el ends here
